### ISSUE TITLE
Въпрос по задача 1 от домашно 4

### ISSUE THREAD

**Issue by mitkodkn** [elsys/po-homework#367]
Извинете, но не ми стана ясно от условието на задача 1 (домашно 4) каква би могла да бъде грешката, при която програмата да извежда резултат -1. Ще може ли да поясните?
> Да се напише фунция is_prime която приема едно число от целочислен тип и връща 1 ако то е просто, 0 ако не е, **или -­1 при грешка**. В main функцията да се чете едно число от стандартния вход и да се изведе на стандартния изход резултата от извикване на функцията с въведеното число.

**Comment by tborisova** [comment]
Например ако се въведе нещо, което не е от целочислен тип

**Comment by mitkodkn** [comment]
Значи is_prime не трябва да приема число от целочислен тип както пише в условието?

**Comment by tborisova** [comment]
Не, ако не е число от целочислен тип например, тогава трябва да се върне -1. Програмата трябва да приема само числа от целочислен тип

**Comment by DanielVladimirov** [comment]
Здравейте, аз също имам въпрос относно връщането на грешка. Задължително ли е всякакъв вид грешка да се поема от функцията? Питам защото докато да се провери дали е въведено отрицателно число вътре в is_prime е лесно и удобно, проверка на типа входни данни е по-удачно да се направи в main-a, тъй като там се намира входът на програмата ни. И за да съм сигурен, че няма недоразбиране, нямам предвид да не изкарва грешка, а просто main-ът да се занимае с нея.

Имам и още един въпрос - едно и нула приспадаме ли ги към простите числа?

**Comment by mitkodkn** [comment]
@tborisova А ако програмата приема само числа от целочислен тип, как така има възможност число да не е от целочислен тип и да се наложи връщане на -1? 

Например, `scanf("%d", &n);` (където n е въведеното от стандартния вход число), използванo в *main*, приема само целочислен тип числа, а функцията *is_prime* приема параметър, който е от тип *int* (също целочислен тип). 

Може би на мен нещо ми убягва в разбирането, но не ми е ясно как е допустимо *is_prime* да приеме число, което **не** е от целочислен тип, при положение, че, както Вие казахте, програмата трябва да приема **само** числа от целочислен тип? :)

**Comment by tborisova** [comment]
@DanielVladimirov просто да проверите, че потребителят не е въвел буква. Относно едно и нула:

**A prime number (or a prime) is a natural number greater than 1 that has no positive divisors other than 1 and itsel**

 @mitkodkn както казах: функцията трябва да работи само с числа от целочислен тип, т.е. ако потребителя въведе буква или нещо друго - трябва да се върне -1.

**Comment by mitkodkn** [comment]
@tborisova Благодаря!
