### ISSUE TITLE
Въпрос по задача 2 от домашно 4

### ISSUE THREAD

**Issue by DanielVladimirov** [elsys/po-homework#368]
Здравейте, имам въпрос за задача 2 от домашното:

>Да се дефинира функция exact_square, приемаща един аргумент от целочислен тип,
която казва дали даденото число е точен квадрат на друго.

Можем ли да ползваме функцията **sqrt()** от **math.h** и Вие ще компилирате ли програми, съдъжащи този хедър?*(Питам, защото моята версия на Убунту няма този хедър по подразбиране и това ме усъмни, че и Вие не го ползвате.)*

**Edit:**
След малко проучване разбрах, че просто трябва програмата да се компилира с допълнителен таг **-lm**. Все пак искам да знам можем ли да ползваме **math.h** без притеснение.

**Comment by tborisova** [comment]
Здравейте,

може да ползвате math.h, в случая с това домашно обаче не Ви е необходимо. Прегледах домашното Ви и сте се справили и без sqrt().
