### ISSUE TITLE
Въпрос по таблицата Headquarters - A клас

### ISSUE THREAD

**Issue by IvoTod** [elsys/po-homework#478]
В таблицата Headquarters - А клас на моето домашно (15 номер) е написано само че 1ва и 2ра работят. Това означава ли че третата не работи или просто не е проверена все още?

**Comment by tborisova** [comment]
Това означа, че трета не работи.

Поздрави,
  Цветелина Борисова

2015-11-07 16:55 GMT+02:00 IvoTod <notifications@github.com>:

**Comment by IvoTod** [comment]
А право да я поправяме имаме ли?

**Comment by tborisova** [comment]
Здравейте,

може да я оправите и ще бъде полезно за Вас за вбъдеще. Тъй като срока
обаче е минал, няма да Ви дам точки. Сега давам точки само за задачи, които
работят.

Поздрави,
  Цветелина Борисова
