### ISSUE TITLE
Генади не баца

### ISSUE THREAD

**Issue by Catishere** [elsys/po-homework#679]
![image](https://cloud.githubusercontent.com/assets/10299427/12247522/124bf504-b8bd-11e5-9f6c-e142d9b88df2.png)
![image](https://cloud.githubusercontent.com/assets/10299427/12247533/22b48d70-b8bd-11e5-9552-e3507ff49ff7.png)
![image](https://cloud.githubusercontent.com/assets/10299427/12247553/32eb5458-b8bd-11e5-8e5a-365367c3db66.png)

**Comment by Catishere** [comment]
Туес ме учи, че 2*2-1 = 2.

**Comment by nikolatzotchev** [comment]
![legit](https://cloud.githubusercontent.com/assets/14894154/12248265/0547ee6c-b86d-11e5-979a-3786589f54bb.png)

**Comment by nikolatzotchev** [comment]
![image](https://cloud.githubusercontent.com/assets/14894154/12248285/f3984b36-b8c0-11e5-80f7-7c3f443e2a51.png)

**Comment by mutafow** [comment]
![screenshot_97](https://cloud.githubusercontent.com/assets/14894196/12294508/ac82e384-ba03-11e5-9b20-4ddef7f948aa.png)
Някой да е казвал с какви символи трябва да е триъгълника или как да изглежда? Тригълникът си е триъгълник. + това което е написал Виктор как е грешно, като е така по условие + последното домашно е кръстено Домашно 08, а то се оказва 06 по някаква причина и 0 точки.

**Comment by mutafow** [comment]
После що имаме 2ки.

**Comment by migglu** [comment]
Ще разгледаме показаните проблеми и ще ги поправим

**Comment by bankin** [comment]
Здравейте,

За съжаление, г-н Мутафов, не бяхте в часа, за да разберете, че обяснихме част от нещата, без да се заяждаме и написахме доста точки.

Относно 3то домашно - теста бе грешен от наша страна вече е поправен. Да, никъде не сме казвали с какъв точно символ да бъде изписано, но при вашето решение има "Wuwedi n:", което не е към изхода, а на другата картинка има разстояния между точките ".  . . .", вместо да бъде ". ...", за съжаление **съм** писал точки на хора и с двата проблема.. много съм заядлив.. ;(

При 06/08 домашно на г-н Цочев съм написал пълния брой точки, въпреки че програмата не му работи. Ако много държите да изпипваме детайлите, както правите Вие, мога да намаля точките и, когато я предаде поправена(hint: имате проблем при четенето на числата) да му напиша точките_за_втора*0.7, тъй като срокът ще бъде преминал?

**Моля за по-спокоен тон на комуникация!**

Лека и спокойна вечер!

Николай Банкин

**Comment by Catishere** [comment]
При 06/08 домашно на г-н Цочев съм написал пълния брой точки, въпреки че програмата не му работи. hahahaha

**Comment by bankin** [comment]
@Catishere кажете г-н Гьошев?

**Comment by mutafow** [comment]
Да, имам, добре там не претендирам, просто казвам, че си спомням че казахте, че няма значение какъв е символа, за това го сложих. За папката домашно 08,аз съмя кръстил така, не Цочев и нямам точки, защото на нашия клас била 06. За това най-много имам претенции, защото не е много справедливо да имам 2ки заради такива неща.

**Comment by nikolatzotchev** [comment]
Аз какво съм направил ?

**Comment by bankin** [comment]
@nikolatzotchev добавил сте снимки как "Генади не баца", а аз съм признал домашното. #noHardFeelings

@mutafow Окей, да няма значение :) В случая не коментирах името на папката, а снимките на първа задача на @nikolatzotchev как не се показват последните 2 букви от hex числото, което се извежда. Добре, ще оценим домашното, което сте предали в папка 08, просто можехте да го напишете с по-спокоен тон и ние щяхме да реагираме по друг начин. Реално за вас това е 6то домашно(ако гледаме поредността на папките също е така), за В/Г клас е 08, грешката е наша, защото сме го написали само 08 и за двата класа.

@Catishere "При 06/08 домашно на г-н Цочев съм написал пълния брой точки, въпреки че програмата не му работи. hahahaha" - за този коментар питам?

**Comment by nikolatzotchev** [comment]
ми извинявам се това беше деня преди да ви питам след чеса, сега всичко е наред 
#Sorry

**Comment by bankin** [comment]
@nikolatzotchev супер #backInTheGame

**Comment by nikolatzotchev** [comment]
@bankin 
#трияведнагаснимките

**Comment by mutafow** [comment]
@nikolatzotchev #tooCoolToHandle 

Ако съм се изказал по-така съжалявам, не е било нарочно, явно така е прозвучало, не съм искал.

**Comment by nikolatzotchev** [comment]
@mutafow anonimen hater

**Comment by bankin** [comment]
@mutafow #gg #wp #izi

Само @Catishere остана да се скатава.
